# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Yaswanthkumar Sirumugai Karunakaran
title: Master's Student in Embedded Systems Engineering
email: yaswanthsk04@gmail.com
website: yaswanthsk04.github.io

# Dark Mode (true/false/never)
darkmode: false

# Social links
#twitter_username: facespics
github_username:  yaswanthsk04
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
#instagram_username: jameswgrant
linkedin_username: yaswanthkumar-s-k
# xing_username: jekyll
# pinterest_username: jekyll
#youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
#additional_links:
#- title: itsgoingto.be
  #icon: fas fa-globe
  #url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile_pic.jpeg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name is Yaswanthkumar and I'm a Master's Student in Embeeded Systems Engineering at University of Freiburg. 
  
  I am an Innovative and Organized Electrical & Electronics Engineer (Embedded Systems) who worked at BOSCH GLOBAL SOFTWARE TECHNOLOGY, Coimbatore as BSW Developer for Electric Steering Systems of Commercial Vehicles. I am currently working as Work Student at ETAS, where I am currently focusing on containerizing Development by using Docker for Simulation Engine Development. 
  
  I am also exploring my interest in the field of Automotive Electronics & Embedded systems for the past 5 years, seeking new problem statements to figure out effective & novel solutions. As an Innovator, I work on various research on different domains such as Automotive Electronics to AI/ML resulting in 3 Research Publications and 1 patent which is under review.

  I am most skilled in: <mark>Automotive Software Development</mark> and <mark>Embedded Systems Pizza</mark>

content:
  - title: Projects
  layout: list
  content:
    - layout: left
      title: Vector Tools Automation
      caption: Mar 2021 - Jun 2021
      description: |
        Developed a Python-based software module to automate test case validation on Vector Tools (CANape, CANoe). This included a customized GUI for user input, automating testing using WIN32 API, and exporting verified results. Outcomes include automated testing validation for individual test cases and user parameterization up to 5 inputs.

    - layout: left
      title: Underwater ROV to Detect Drowning People
      caption: Jun 2020 - Dec 2020
      description: |
        Developed a semi-autonomous Remote Operated Vehicle (ROV) to detect drowning people using sonar, thermal, and camera detection methods. The project involved designing a water-proof casing, interfacing sensors to an onboard processor, and employing computer vision with Yolo algorithms for human detection with an accuracy of 92%.

    - layout: left
      title: Human Assistance Rover
      caption: Feb 2020 - May 2020
      description: |
        Built a people follower robot using GPS coordinates and Bluetooth for personal assistance. The prototype featured a 4-wheeled rover with a rocker bogie mechanism for stability, utilizing a Jetson Nano development board, GPS, and Bluetooth sensors.

    - layout: left
      title: Charge As A Service | EV Charging Station
      caption: Aug 2019 - Dec 2019
      description: |
        Implemented an AI and Blockchain technology solution for Electric Vehicle (EV) charging stations to predict and manage power demand. The project included developing a blockchain-based billing system and using CAN Protocol, I2C, and SPI for communication between the EV and the charging station.


  - title: Experience
  layout: list
  content:
    - layout: left
      title: Work Student at ETAS
      caption: Apr 2023 - Present
      description: |
        Focus on containerizing Development using Docker for Simulation Engine Development. Work includes Docker, Conan packages, MSVC and GCC compilers, CMake, and automated build processes.

    - layout: left
      title: Associate Software Engineer at Bosch Global Software Technologies
      caption: Jul 2021 - Aug 2022
      description: |
        Developer for Servotwin Electrohydraulic Steering Systems, including platform software development, ECU components, and software testing using CAPL, Python, Jenkins, and Bitbucket.

    - layout: left
      title: Project Trainee at Bosch Global Software Technologies
      caption: Mar 2021 - Jun 2021
      description: |
        Testing Automation for Steering ECU & Instrument Cluster Models, including CAPL and Python-based automation for various communication protocols.


  - title: Education
  layout: list
  content:
    - layout: left
      title: University of Freiburg
      caption: Oct 2022 - Present
      sub_title: M.Sc. Embedded Systems Engineering
      description: |
        Focused on Embedded Systems, Microcontrollers and Microprocessors, Computer Architecture, Mobile Robotics, and AI/ML.

    - layout: left
      title: Kumaraguru College of Technology
      caption: Aug 2017 - Jun 2021
      sub_title: Bachelor's degree in Electrical and Electronics Engineering
      description: |
        Active leadership roles including President of the Student Body Association of the EEE department and Member of IoT and Embedded systems domain at IQube.

  - title: Skills
  layout: list
  content:
    - layout: left
      title: Technical Skills
      description: |
        - Automation: Proficient in automating tasks to increase efficiency and accuracy.
        - Electronics: Solid understanding of electronic systems and components.
        - CAPL: Experienced in using CAPL for automotive software testing and development.
        - Documentation: Skilled in creating detailed technical documents.
        - Computer-Aided Design (CAD): Proficient in CAD tools for design and simulation.
        - Artificial Intelligence (AI): Knowledge in AI principles and applications.
        - Agile Project Management: Experienced in Agile methodologies for project management.
        - Programming Languages: Proficient in C and C++ for software development.
        - Embedded Systems: Extensive knowledge in designing and developing embedded systems.

    - layout: left
      title: Software & Tools
      description: |
        - Vector Tools (CANape, CANoe): Developed automation modules for testing.
        - Python: Extensive use in automation, testing, and GUI development.
        - Jenkins & Bitbucket: Used for continuous integration and version control.
        - Docker: Utilized for containerizing development environments.
        - MATLAB/Simulink: Employed for simulation and model-based design.
        - CAD Tools: Experience with various CAD tools for electronic and mechanical design.

  - title: A Little More About Me
    layout: text
    content: | 
      Alongside my interests in networks and software engineering some of my other interests and hobbies are:
      - Treckking
      - Gaming
      - KnittTraveling

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
